"""Declarative description of every diagram. Rendered by generate_diagrams.py.

Every class name and every member label here has to exist in the source. The
--check mode of the renderer verifies that, so a diagram cannot go on
describing a method that was renamed or removed.

A node is placed on a grid: col is the column, row is the row. Column widths and
row heights are derived from the content, so only the relative position matters.

Edge kinds:
    inherits  hollow triangle, points at the abstraction
    holds     hollow diamond at the owner, solid line
    uses      dashed line, open arrow
"""

from generate_diagrams import Diagram, Edge, Node


def N(key, name, col, row, stereotype="", members=()):
    # The stereotype is optional, so allow the member list in its place.
    if not isinstance(stereotype, str):
        stereotype, members = "", stereotype
    return Node(key=key, name=name, col=col, row=row, stereotype=stereotype,
                members=list(members))


DIAGRAMS = [
    Diagram(
        slug="singleton", title="Singleton", category="creational",
        caption="One instance, created on first access, shared by every caller.",
        nodes=[
            N("client", "Client", 0, 0, members=["LazySingleton.Instance"]),
            N("lazy", "LazySingleton", 1, 0, "sealed",
              ["- Lazy<LazySingleton> _instance", "+ Instance : LazySingleton",
               "+ DoSomething() : void"]),
            N("lock", "LockSingleton", 1, 1, "sealed",
              ["- volatile LockSingleton? _instance", "- object _lock",
               "+ Instance : LockSingleton", "+ DoSomething() : void"]),
        ],
        edges=[Edge("client", "lazy", "uses", "Instance"),
               Edge("client", "lock", "uses")],
    ),
    Diagram(
        slug="factory-method", title="Factory Method", category="creational",
        caption="The factory decides which concrete type the caller receives.",
        nodes=[
            N("factory", "OperatingSystemFactory", 0, 0, "static",
              ["+ CreateOperatingSystem(osType) : IOperatingSystem"]),
            N("iface", "IOperatingSystem", 1, 0, "interface",
              ["+ Configure() : void", "+ DisplayInfo() : void"]),
            N("win", "WindowsOS", 1, 1, ["+ Configure() : void", "+ DisplayInfo() : void"]),
            N("linux", "LinuxOS", 2, 1, ["+ Configure() : void", "+ DisplayInfo() : void"]),
        ],
        edges=[Edge("factory", "iface", "uses", "creates"),
               Edge("win", "iface", "inherits"),
               Edge("linux", "iface", "inherits")],
    ),
    Diagram(
        slug="abstract-factory", title="Abstract Factory", category="creational",
        caption="Each factory produces one coherent family of products.",
        nodes=[
            N("ifact", "IOperatingSystemFactory", 0, 0, "interface",
              ["+ CreateOperatingSystem() : IOperatingSystem"]),
            N("iprod", "IOperatingSystem", 2, 0, "interface",
              ["+ Configure() : void", "+ DisplayInfo() : void"]),
            N("wfact", "WindowsOSFactory", 0, 1, ["+ CreateOperatingSystem()"]),
            N("lfact", "LinuxOSFactory", 1, 1, ["+ CreateOperatingSystem()"]),
            N("win", "WindowsOS", 2, 1, ["+ Configure() : void"]),
            N("linux", "LinuxOS", 3, 1, ["+ Configure() : void"]),
        ],
        edges=[Edge("wfact", "ifact", "inherits"), Edge("lfact", "ifact", "inherits"),
               Edge("win", "iprod", "inherits"), Edge("linux", "iprod", "inherits"),
               Edge("ifact", "iprod", "uses", "creates")],
    ),
    Diagram(
        slug="builder", title="Builder", category="creational",
        caption="Each step returns the builder, so the calls chain into one expression.",
        nodes=[
            N("iface", "IOperatingSystemConfigBuilder", 0, 0, "interface",
              ["+ SetOSName(osName)", "+ SetVersion(version)",
               "+ SetFileSystem(fileSystem)", "+ EnableFirewall(enable)",
               "+ SetNetworkSettings(networkSettings)",
               "+ Build() : OperatingSystemConfig"]),
            N("builder", "OperatingSystemConfigBuilder", 0, 1,
              ["- OperatingSystemConfig _config", "+ Build() : OperatingSystemConfig"]),
            N("product", "OperatingSystemConfig", 1, 1, "product",
              ["+ OSName : string", "+ Version : string", "+ FileSystem : string",
               "+ IsFirewallEnabled : bool", "+ NetworkSettings : string",
               "+ DisplayConfig() : void"]),
        ],
        edges=[Edge("builder", "iface", "inherits"),
               Edge("builder", "product", "holds", "builds")],
    ),
    Diagram(
        slug="prototype", title="Prototype", category="creational",
        caption="A new instance is produced by copying an existing one.",
        nodes=[
            N("iface", "IPrototype<T>", 0, 0, "interface", ["+ Clone() : T"]),
            N("impl", "OperatingSystemSettings", 0, 1,
              ["+ OSName : string", "+ Version : string",
               "+ Clone() : OperatingSystemSettings", "+ DisplaySettings() : void"]),
        ],
        edges=[Edge("impl", "iface", "inherits")],
    ),
    Diagram(
        slug="adapter", title="Adapter", category="structural",
        caption="Each adapter presents an existing class through the wanted interface.",
        nodes=[
            N("iface", "ISystemInfo", 1, 0, "interface", ["+ GetSystemDetails() : string"]),
            N("wa", "WindowsAdapter", 0, 1,
              ["- WindowsOS _windowsOS", "+ GetSystemDetails() : string"]),
            N("la", "LinuxAdapter", 2, 1,
              ["- LinuxOS _linuxOS", "+ GetSystemDetails() : string"]),
            N("win", "WindowsOS", 0, 2, "adaptee", ["+ RetrieveWindowsInfo() : string"]),
            N("linux", "LinuxOS", 2, 2, "adaptee", ["+ FetchLinuxInfo() : string"]),
        ],
        edges=[Edge("wa", "iface", "inherits"), Edge("la", "iface", "inherits"),
               Edge("wa", "win", "holds"), Edge("la", "linux", "holds")],
    ),
    Diagram(
        slug="bridge", title="Bridge", category="structural",
        caption="Abstraction and implementation vary on separate axes.",
        nodes=[
            N("abs", "FileManager", 0, 0, "abstract",
              ["# IFileSystem _fileSystem", "+ SaveFile(fileName, content) : void",
               "+ ReadFile(fileName) : string"]),
            N("impl", "IFileSystem", 1, 0, "interface",
              ["+ WriteToFile(fileName, content)", "+ ReadFromFile(fileName) : string"]),
            N("ref", "TextFileManager", 0, 1,
              ["+ SaveFile(fileName, content)", "+ ReadFile(fileName) : string"]),
            N("win", "WindowsFileSystem", 1, 1,
              ["+ WriteToFile(...)", "+ ReadFromFile(...)"]),
            N("linux", "LinuxFileSystem", 2, 1,
              ["+ WriteToFile(...)", "+ ReadFromFile(...)"]),
        ],
        edges=[Edge("ref", "abs", "inherits"), Edge("win", "impl", "inherits"),
               Edge("linux", "impl", "inherits"), Edge("abs", "impl", "holds")],
    ),
    Diagram(
        slug="composite", title="Composite", category="structural",
        caption="A leaf and a branch answer the same calls.",
        nodes=[
            N("comp", "FileSystemComponent", 0, 0, "abstract",
              ["+ Name : string", "+ Display(depth) : void", "+ CalculateSize() : long"]),
            N("leaf", "File", 0, 1, "leaf",
              ["- long _size", "+ Display(depth) : void", "+ CalculateSize() : long"]),
            N("branch", "Directory", 1, 1, "composite",
              ["- List<FileSystemComponent> _children", "+ Add(component) : void",
               "+ Remove(component) : void", "+ CalculateSize() : long"]),
        ],
        edges=[Edge("leaf", "comp", "inherits"), Edge("branch", "comp", "inherits"),
               Edge("branch", "comp", "holds", "children")],
    ),
    Diagram(
        slug="decorator", title="Decorator", category="structural",
        caption="Each decorator wraps a notification and adds one responsibility.",
        nodes=[
            N("abs", "Notification", 1, 0, "abstract", ["+ Send(message) : void"]),
            N("basic", "BasicNotification", 0, 1, ["+ Send(message) : void"]),
            N("dec", "NotificationDecorator", 2, 1, "abstract",
              ["# Notification _notification"]),
            N("log", "LoggingDecorator", 1, 2,
              ["+ Send(message) : void", "- Log(message) : void"]),
            N("enc", "EncryptionDecorator", 2, 2,
              ["+ Send(message) : void", "- Encrypt(message) : string"]),
            N("prio", "PrioritizationDecorator", 3, 2,
              ["+ Send(message) : void", "- Prioritize(message) : string"]),
        ],
        edges=[Edge("basic", "abs", "inherits"), Edge("dec", "abs", "inherits"),
               Edge("dec", "abs", "holds", "wraps"),
               Edge("log", "dec", "inherits"), Edge("enc", "dec", "inherits"),
               Edge("prio", "dec", "inherits")],
    ),
    Diagram(
        slug="facade", title="Facade", category="structural",
        caption="One entry point in front of three collaborating classes.",
        nodes=[
            N("client", "Client", 0, 0, members=["facade.ProcessFile(...)"]),
            N("facade", "FileManagerFacade", 1, 0,
              ["- FileReader _fileReader", "- FileWriter _fileWriter",
               "- FileValidator _fileValidator",
               "+ ProcessFile(filePath, newContent) : void"]),
            N("val", "FileValidator", 2, 0, ["+ Validate(filePath) : bool"]),
            N("read", "FileReader", 2, 1, ["+ ReadFile(filePath) : string"]),
            N("write", "FileWriter", 2, 2, ["+ WriteFile(filePath, content) : void"]),
        ],
        edges=[Edge("client", "facade", "uses"), Edge("facade", "val", "holds"),
               Edge("facade", "read", "holds"), Edge("facade", "write", "holds")],
    ),
    Diagram(
        slug="flyweight", title="Flyweight", category="structural",
        caption="The factory returns a shared instance for a key it has already seen.",
        nodes=[
            N("client", "Client", 0, 0, members=["GetFileMetadata(type, owner)"]),
            N("factory", "FileMetadataFactory", 1, 0,
              ["- Dictionary<string, IFileMetadata> _metadataCache", "- object _lock",
               "+ GetFileMetadata(fileType, owner)", "+ CacheCount : int",
               "+ Output : TextWriter"]),
            N("iface", "IFileMetadata", 2, 0, "interface", ["+ DisplayFileInfo() : void"]),
            N("impl", "FileMetadata", 2, 1, "flyweight",
              ["- string _fileType", "- string _owner", "+ DisplayFileInfo() : void"]),
        ],
        edges=[Edge("client", "factory", "uses"),
               Edge("factory", "iface", "uses", "returns"),
               Edge("impl", "iface", "inherits")],
    ),
    Diagram(
        slug="proxy", title="Proxy", category="structural",
        caption="The proxy checks the role, then creates the resource on first use.",
        nodes=[
            N("iface", "IResource", 1, 0, "interface", ["+ Access() : void"]),
            N("proxy", "ResourceProxy", 0, 1,
              ["- Resource? _realResource", "- string _userRole",
               "+ Access() : void", "- HasAccess() : bool"]),
            N("real", "Resource", 2, 1, "real subject", ["+ Access() : void"]),
        ],
        edges=[Edge("proxy", "iface", "inherits"), Edge("real", "iface", "inherits"),
               Edge("proxy", "real", "holds", "lazy")],
    ),
    Diagram(
        slug="chain-of-responsibility", title="Chain of Responsibility",
        category="behavioral",
        caption="Each handler either deals with the request or passes it on.",
        nodes=[
            N("abs", "FileOperationHandler", 0, 0, "abstract",
              ["# FileOperationHandler _nextHandler", "+ SetNext(nextHandler) : void",
               "+ HandleRequest(operationType, fileName) : void"]),
            N("auth", "AuthorizationHandler", 0, 1, ["+ HandleRequest(...)"]),
            N("val", "ValidationHandler", 1, 1, ["+ HandleRequest(...)"]),
            N("log", "LoggingHandler", 2, 1, ["+ HandleRequest(...)"]),
        ],
        edges=[Edge("auth", "abs", "inherits"), Edge("val", "abs", "inherits"),
               Edge("log", "abs", "inherits"), Edge("abs", "abs", "holds")],
    ),
    Diagram(
        slug="command", title="Command", category="behavioral",
        caption="The invoker holds a request as an object and never knows the receiver.",
        nodes=[
            N("invoker", "FileInvoker", 0, 0, "invoker",
              ["- List<ICommand> _history", "+ History : IReadOnlyList<ICommand>",
               "+ Execute(command) : void", "+ Undo() : bool", "+ UndoAll() : void"]),
            N("iface", "ICommand", 1, 0, "interface",
              ["+ Execute() : void", "+ Undo() : void"]),
            N("create", "CreateFileCommand", 1, 1,
              ["- FileSystemReceiver _fileSystem", "- string _filename"]),
            N("write", "WriteFileCommand", 2, 1,
              ["- string _filename", "- string _content"]),
            N("delete", "DeleteFileCommand", 3, 1,
              ["- FileSystemReceiver _fileSystem", "- string _filename"]),
            N("receiver", "FileSystemReceiver", 2, 2, "receiver",
              ["+ CreateFile(filename)", "+ WriteFile(filename, content)",
               "+ DeleteFile(filename)"]),
        ],
        edges=[Edge("invoker", "iface", "holds"),
               Edge("create", "iface", "inherits"), Edge("write", "iface", "inherits"),
               Edge("delete", "iface", "inherits"),
               Edge("write", "receiver", "uses")],
    ),
    Diagram(
        slug="interpreter", title="Interpreter", category="behavioral",
        caption="Each rule of the grammar is one class that can interpret a file.",
        nodes=[
            N("iface", "IExpression", 0, 0, "interface", ["+ Interpret(file) : bool"]),
            N("ext", "ExtensionFilter", 0, 1, "terminal",
              ["- string _extension", "+ Interpret(file) : bool"]),
            N("name", "FilenameFilter", 1, 1, "terminal",
              ["- string _filename", "+ Interpret(file) : bool"]),
            N("ctx", "File", 2, 1, "context",
              ["+ Name : string", "+ Extension : string"]),
        ],
        edges=[Edge("ext", "iface", "inherits"), Edge("name", "iface", "inherits"),
               Edge("iface", "ctx", "uses", "reads")],
    ),
    Diagram(
        slug="iterator", title="Iterator", category="behavioral",
        caption="Traversal is separated from the structure being traversed.",
        nodes=[
            N("coll", "IFileSystemCollection", 0, 0, "interface",
              ["+ CreateIterator() : IIterator<IFileSystemElement>"]),
            N("iter", "IIterator<T>", 1, 0, "interface",
              ["+ HasNext() : bool", "+ Next() : T"]),
            N("dir", "Directory", 0, 1,
              ["- List<IFileSystemElement> _elements", "+ AddElement(element) : void",
               "+ CreateIterator() : IIterator<IFileSystemElement>"]),
            N("elem", "IFileSystemElement", 2, 1, "interface",
              ["+ Name : string", "+ PrintDetails() : void"]),
            N("file", "File", 2, 2, ["+ Name : string", "+ PrintDetails() : void"]),
        ],
        edges=[Edge("dir", "coll", "inherits"), Edge("coll", "iter", "uses", "creates"),
               Edge("iter", "elem", "uses", "yields"), Edge("file", "elem", "inherits")],
    ),
    Diagram(
        slug="mediator", title="Mediator", category="behavioral",
        caption="Colleagues talk to the mediator, never to one another.",
        nodes=[
            N("iface", "IFileManager", 1, 0, "interface",
              ["+ CreateFile(filename)", "+ OpenFile(filename)",
               "+ DeleteFile(filename)", "+ Notify(sender, eventCode)"]),
            N("med", "FileManager", 1, 1, "concrete mediator",
              ["- FileExplorer _fileExplorer",
               "- FileOperationHandler _fileOperationHandler",
               "- Logger _logger"]),
            N("explorer", "FileExplorer", 0, 2, "colleague",
              ["+ CurrentFile : string?", "+ SelectFile(filename)", "+ CreateFile()"]),
            N("handler", "FileOperationHandler", 1, 2, "colleague",
              ["+ Operations : IReadOnlyList<string>", "+ IsAttached : bool"]),
            N("logger", "Logger", 2, 2, "colleague",
              ["+ Entries : IReadOnlyList<string>", "+ Log(message)"]),
        ],
        edges=[Edge("med", "iface", "inherits"), Edge("med", "explorer", "holds"),
               Edge("med", "handler", "holds"), Edge("med", "logger", "holds")],
    ),
    Diagram(
        slug="memento", title="Memento", category="behavioral",
        caption="The caretaker keeps snapshots it cannot read into, one stack per direction.",
        nodes=[
            N("orig", "FileEditor", 0, 0, "originator",
              ["+ Content : string", "+ Write(content) : void",
               "+ Save() : FileMemento", "+ Restore(memento) : void"]),
            N("care", "FileHistory", 2, 0, "caretaker",
              ["- Stack<FileMemento> _undoStack", "- Stack<FileMemento> _redoStack",
               "- FileEditor _fileEditor", "+ Save()", "+ Undo()", "+ Redo()"]),
            N("mem", "FileMemento", 1, 1, "memento", ["+ Content : string"]),
        ],
        edges=[Edge("orig", "mem", "uses", "creates"), Edge("care", "mem", "holds"),
               Edge("care", "orig", "holds")],
    ),
    Diagram(
        slug="observer", title="Observer", category="behavioral",
        caption="The subject notifies a snapshot of its observers, taken under a lock.",
        nodes=[
            N("subject", "IFileSubject", 0, 0, "interface",
              ["+ RegisterObserver(observer)", "+ UnregisterObserver(observer)",
               "+ NotifyObservers(fileName, changeType)"]),
            N("obs", "IFileObserver", 2, 0, "interface",
              ["+ Update(fileName, changeType) : void"]),
            N("watcher", "FileWatcher", 0, 1,
              ["- List<IFileObserver> _observers", "- object _observersLock",
               "+ StartWatching(path) : void", "+ StopWatching() : void"]),
            N("console", "ConsoleLogger", 2, 1, ["+ Update(fileName, changeType)"]),
            N("email", "EmailNotifier", 3, 1, ["+ Update(fileName, changeType)"]),
        ],
        edges=[Edge("watcher", "subject", "inherits"),
               Edge("console", "obs", "inherits"), Edge("email", "obs", "inherits"),
               Edge("subject", "obs", "uses", "notifies")],
    ),
    Diagram(
        slug="state", title="State", category="behavioral",
        caption="The context delegates, and the state chooses the next state.",
        nodes=[
            N("ctx", "FileContext", 0, 0, "context",
              ["+ State : IFileState", "+ Output : TextWriter",
               "+ Open()", "+ Close()", "+ Edit()"]),
            N("iface", "IFileState", 1, 0, "interface",
              ["+ Open(context)", "+ Close(context)", "+ Edit(context)"]),
            N("created", "CreatedState", 1, 1, ["+ Open(context)", "+ Edit(context)"]),
            N("opened", "OpenedState", 2, 1, ["+ Edit(context)", "+ Close(context)"]),
            N("closed", "ClosedState", 3, 1, ["+ Open(context)", "+ Close(context)"]),
        ],
        edges=[Edge("ctx", "iface", "holds"), Edge("created", "iface", "inherits"),
               Edge("opened", "iface", "inherits"), Edge("closed", "iface", "inherits")],
    ),
    Diagram(
        slug="strategy", title="Strategy", category="behavioral",
        caption="The algorithm is selected at run time and swapped through one interface.",
        nodes=[
            N("ctx", "FileCompressor", 0, 0, "context",
              ["- ICompressionStrategy? _compressionStrategy",
               "+ SetCompressionStrategy(strategy)", "+ CompressFile(filePath) : void"]),
            N("iface", "ICompressionStrategy", 1, 0, "interface",
              ["+ Compress(filePath) : void"]),
            N("zip", "ZipCompressionStrategy", 1, 1, ["+ Compress(filePath) : void"]),
            N("gzip", "GZipCompressionStrategy", 2, 1, ["+ Compress(filePath) : void"]),
        ],
        edges=[Edge("ctx", "iface", "holds"), Edge("zip", "iface", "inherits"),
               Edge("gzip", "iface", "inherits")],
    ),
    Diagram(
        slug="template-method", title="Template Method", category="behavioral",
        caption="The base class fixes the order, the subclasses fill in the steps.",
        nodes=[
            N("abs", "FileProcessor", 0, 0, "abstract",
              ["+ ProcessFile(filePath) : void", "# OpenFile(filePath) : void",
               "# ReadFileContent() : string", "# ProcessContent(content) : void",
               "# CloseFile() : void"]),
            N("text", "TextFileProcessor", 0, 1,
              ["- StreamReader? _reader", "# ReadFileContent() : string",
               "# ProcessContent(content) : void"]),
            N("csv", "CsvFileProcessor", 1, 1,
              ["- StreamReader? _reader", "# ReadFileContent() : string",
               "# ProcessContent(content) : void"]),
        ],
        edges=[Edge("text", "abs", "inherits"), Edge("csv", "abs", "inherits")],
    ),
    Diagram(
        slug="visitor", title="Visitor", category="behavioral",
        caption="Adding an operation means adding a visitor, without touching the elements.",
        nodes=[
            N("elem", "IFileSystemElement", 0, 0, "interface",
              ["+ Accept(visitor) : void"]),
            N("visitor", "IFileSystemVisitor", 2, 0, "interface",
              ["+ Visit(file) : void", "+ Visit(directory) : void"]),
            N("file", "File", 0, 1,
              ["+ Name : string", "+ Size : long", "+ Accept(visitor) : void"]),
            N("dir", "Directory", 1, 1,
              ["+ Elements : List<IFileSystemElement>", "+ AddElement(element) : void",
               "+ Accept(visitor) : void"]),
            N("listing", "FileListingVisitor", 2, 1, ["+ Visit(file) : void"]),
            N("size", "SizeCalculationVisitor", 3, 1,
              ["+ TotalSize : long", "+ Visit(file) : void"]),
        ],
        edges=[Edge("file", "elem", "inherits"), Edge("dir", "elem", "inherits"),
               Edge("listing", "visitor", "inherits"), Edge("size", "visitor", "inherits"),
               Edge("elem", "visitor", "uses", "accepts")],
    ),
]
